// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpJUkzYK67hi-vYpUcdwhkBzea8wPmjs',
    appId: '1:111740807695:web:a21467ff3d085b0689517a',
    messagingSenderId: '111740807695',
    projectId: 'hapi-b44bb',
    authDomain: 'hapi-b44bb.firebaseapp.com',
    storageBucket: 'hapi-b44bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_EvpmhwQHaccxdEE6kFpmsaBra7IUMY',
    appId: '1:111740807695:android:ef0a9f3c91ca310689517a',
    messagingSenderId: '111740807695',
    projectId: 'hapi-b44bb',
    storageBucket: 'hapi-b44bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB524CJOh51SOGI7WWy8Amn61cuMzIG7FY',
    appId: '1:111740807695:ios:4d9645075528c3d489517a',
    messagingSenderId: '111740807695',
    projectId: 'hapi-b44bb',
    storageBucket: 'hapi-b44bb.firebasestorage.app',
    iosBundleId: 'com.example.hapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB524CJOh51SOGI7WWy8Amn61cuMzIG7FY',
    appId: '1:111740807695:ios:4d9645075528c3d489517a',
    messagingSenderId: '111740807695',
    projectId: 'hapi-b44bb',
    storageBucket: 'hapi-b44bb.firebasestorage.app',
    iosBundleId: 'com.example.hapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmpJUkzYK67hi-vYpUcdwhkBzea8wPmjs',
    appId: '1:111740807695:web:c7976ca78fee821d89517a',
    messagingSenderId: '111740807695',
    projectId: 'hapi-b44bb',
    authDomain: 'hapi-b44bb.firebaseapp.com',
    storageBucket: 'hapi-b44bb.firebasestorage.app',
  );
}
